[workspace]
members = [
    "node",
    "pallets/brands",
    "pallets/consumers",
    "pallets/ecosystems",
    "pallets/points",
    "pallets/promos",
    "pallets/gcdex",
    "runtime",
]
[profile.release]
panic = "unwind"
